### ISSUE TITLE
Refreshing playlist if any changes were made on the server.

### ISSUE THREAD

**Issue by kreonjr** [podverse/podverse#140]

**Comment by mitchdowney** [comment]
Refreshing all playlists has been pushed to the autoDownloadUpdate. On app load and when using the refreshControl on the PodcastTableVC, all playlists will refresh. If the total number of playlistItems for the playlist on the server is different than the total number of playlistItems for the playlist in CoreData, then download the latest version of the playlist.

This feature could be improved, since checking the total number of playlistItems is not a true test. I think the code pushed to autoDownloadUpdate can work for now though...

**Comment by kreonjr** [comment]
Fixed
