### ISSUE TITLE
subscribed shows, has value "false" for issubscribed

### ISSUE THREAD

**Issue by morad** [podverse/podverse#144]
Hello,

What is the best way to determine if the show is subscribed or not? Is it if feedurl value exist in CoreData Podcast entity? I have used isSubscribed object but it seems it is not always accurate. Some podcasts that exists in CoreData with feedurl has "isSubscribed" value as 0.

Thanks

**Comment by mitchdowney** [comment]
Thanks for the question @morad! To be honest the app is not finished yet and there may be issues to debug.

Currently the app has two situations where XYZ podcast may be saved to CoreData:

1) when you subscribe to XYZ podcast, isSubscribed is set to 1, and the XYZ podcast feed is parsed and saved to CoreData.

2) if you subscribe to a playlist, and that playlist contains an episode or clip from XYZ podcast (as a playlistItem), then the podcast / episode / clip are all added to CoreData, but the podcast.isSubscribed value is 0. (This needs to be cleaned up to ensure podcasts do not unnecessarily hang around in CoreData).

But since this is a work-in-progress, it is possible you are seeing isSubscribed = 0 at unintended times.

Cheers

**Comment by mitchdowney** [comment]
I believe this has been resolved. The app is still unfinished however :)
