### ISSUE TITLE
How do we implement alpha testing? (invite only user testing)

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#63]
My goal is to get Podverse in the hands/iPhones/iPads of friends and family in January 2016. How does one do invite-only alpha testing, when all apps have to go through the App Store?

**Comment by mitchdowney** [comment]
Google: ios app beta testing

**Comment by kreonjr** [comment]
I have found and created an account with a software suite called Fabric that provides a multitude of capabilities among which one is Beta testing. Let talk next time about this since it is a very easy process as I have found out. All I need is an email to send the invite and the testers just follow the steps in the email. Piece of cake

**Comment by mitchdowney** [comment]
Fabric = awesome
