### ISSUE TITLE
Refresher loading spinner should disappear after podcast feeds have been parsed

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#95]
The refresher never goes away on the PodcastTableViewController.

**Comment by mitchdowney** [comment]
Ideally the refresher should go away after all podcast feeds have completed refreshing. I'm not sure how to handle this yet...

**Comment by kreonjr** [comment]
Problem is the podcastTableVC is calling the appdelegate method to refresh the feed so as soon as the refresh is complete, the feedParsingComplete method is called but podcastTableVC is not a delegate of PVFeedParsing so that method never gets called. We need to find a way to notify the podcastTableVC that the parsing is complete.

**Comment by kreonjr** [comment]
PR to fix issue is in #116
